server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
    
    location /api/ {
        proxy_pass http://pfe_backend:8082/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Origin "";
        proxy_set_header Referer "";
    }
    
    location /admin/ {
        proxy_pass http://pfe_backend:8082/admin/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Origin "";
        proxy_set_header Referer "";
        proxy_set_header Cookie $http_cookie;  # ← ajoute cette ligne
    }
    
    location /agent/ {
        proxy_pass http://pfe_backend:8082/agent/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Origin "";
        proxy_set_header Referer "";
        proxy_set_header Cookie $http_cookie;  # ← ici aussi
    }
    
    location /auth/ {
        proxy_pass http://pfe_backend:8082/auth/;   # ← slash final ajouté
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Origin "";                  # ← ajouté
        proxy_set_header Referer "";
        proxy_set_header Cookie $http_cookie;                 # ← ajouté
    }
}